# .github/workflows/swiftlint.yml
name: SwiftLint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: SwiftLint
      run: swiftlint lint --config .swiftlint.yml --reporter github-actions-logging