# .github/workflows/swiftlint.yml
name: SwiftLint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run SwiftLint
        env:
          SWIFTLINT_ENABLE_WRITE_PACKAGE_DIRECTORY: "yes"
        run: swift package plugin swiftlint --quiet