# .github/workflows/swiftlint.yml
name: SwiftLint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install SwiftLint
        run: |
          sudo apt-get update
          sudo apt-get install -y swiftlint
      
      - name: Run SwiftLint
        run: swiftlint lint --quiet --reporter github-actions-logging